import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideDrawer from "@/components/SideDrawer";
import { GlobalContext } from "@/hooks/globalContext";



export const metadata: Metadata = {
  title: "Next :: Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body >
     
          <Header  />
          {children}
          <Footer />
      </body>
    </html>
  );
}
